{
  try {
    debug="before evaluate condition";
    boolean ret=meta.getCondition().evaluate(row);
    debug="after evaluate condition";
    return ret;
  }
 catch (  Exception e) {
    String message="Unexpected error found in evaluation function : " + e.toString();
    logError(message);
    logError("Error occurred for row: " + row);
    logError(Const.getStackTracker(e));
    throw new KettleException(message,e);
  }
}
