{
  try {
    throw new IdNotFoundException(cause,objectName,pathToObject,objectType);
  }
 catch (  IdNotFoundException testedException) {
    Throwable cause=testedException.getCause();
    assertEquals(this.cause,testedException.getCause());
    assertTrue(testedException.getMessage().contains(causeExceptionMessage));
    assertEquals(objectName,testedException.getObjectName());
    assertEquals(pathToObject,testedException.getPathToObject());
    assertEquals(objectType,testedException.getObjectType());
  }
}
