{
  try {
    return doCall();
  }
 catch (  Exception e) {
    condition.set(false);
    throw e;
  }
}
