{
  try {
    testee.throwSomeException();
  }
 catch (  RuntimeException actual) {
    assertEquals("did not get the expected runtime exception",rte,actual);
  }
}
